# Base on image_full_name (e.g., ubuntu:18.04) docker image
FROM python:3.8.12

# Switch to root
USER root

# Create working dir
RUN mkdir -p /usr/local/source/UbiFL

# Set up project root working path
ENV UBIFL_HOME=/usr/local/source/UbiFL

# Address docker-compose not print the print() message
ENV PYTHONUNBUFFERED=1

# Change working dir
WORKDIR /usr/local/source/UbiFL

# Copy all sources files to workdir
ADD ./ /usr/local/source/UbiFL

# Warnings: This stage will ask github account, so how coud we do?
# Prepare required project folder
WORKDIR /usr/local/source/UbiFL
RUN mkdir -p cache \
&& mkdir -p cache/accuracy \
&& mkdir -p cache/loss \
&& mkdir -p cache/test_data \
&& mkdir -p cache/test_data/partition \
&& mkdir -p cache/train_data \
&& mkdir -p cache/train_data/partition \
&& mkdir -p running \
&& mkdir -p running/checkpoints \
&& mkdir -p running/logs

# Install mpi tools
RUN apt update
RUN apt install -y mpi-default-dev

# Prepare project required running system environments
RUN pip3 install -r /usr/local/source/UbiFL/ubifl_server/CI/cpu_server/requirements.txt

# >>>>>>>>>>> Run aggregator_start.sh >>>>>>>>>>>
WORKDIR /usr/local/source/UbiFL/ubifl_server/experiments/fedavg
RUN chmod +x /usr/local/source/UbiFL/ubifl_server/experiments/fedavg/aggregator_start.sh
CMD bash -c "/usr/local/source/UbiFL/ubifl_server/experiments/fedavg/aggregator_start.sh ../configs/cifar10/conf.yml /usr/local/source/UbiFL"

