version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: NCL
      DOCKER_INFLUXDB_INIT_BUCKET: pre_setting
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: TokenForNCLProject
      DOCKER_INFLUXDB_INIT_RETENTION: 30d
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - $PWD/influxdb2/data:/var/lib/influxdb2
      - $PWD/influxdb2/config:/etc/influxdb2