apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
  labels:
    iot: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      iot: aggregator
  template:
    metadata:
      name: aggregator
      labels:
        iot: aggregator
    spec:
      containers:
        - name: aggregator
          image: localhost:32000/iot_aggregator
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator-service
  labels:
    iot: aggregator
spec:
  selector:
    iot: aggregator
  type: NodePort
  ports:
    - name: aggregator-port
      port: 8088
      targetPort: 8088
      nodePort: 30003
      protocol: TCP
    

